# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a4210b0728721a7cf9855c029c5c0a80d0be19ce17fdfc0bde6c497910d4c1acec1cbd1c4e141b8ad3f7c37c20dade329df6f9201b3c084ca2d98cb338e52d0

test:
  secret_key_base: c56396f0a2e073a3ccca12353e75fd632fed35ea5d6d70f39d4c9364fa6dd1c66ba198bf42cfd7f65c19b71072097999ce8194de81180243069cfe74561e88aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
